
package SubTelas.Func;

import Commun.TextPrompt;
import Dao.FuncionarioDao;
import Produto.Funcionario;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author cleyt
 */
public class TelaAlterarFunc extends javax.swing.JInternalFrame {
    
    public TelaAlterarFunc() {
        initComponents();
        prencherTabela();
        TextPrompt tx = new TextPrompt("Pesquisar", txtPesquisar);
    }
    
    public TelaAlterarFunc(int atl){
        initComponents();       
        TextPrompt tx = new TextPrompt("Pesquisar", txtPesquisar);
        btnPesquisar.doClick();
        repaint();
        System.err.println("as");
    }
 
    private void prencherTabela() {
        //Prenchendno a tabela assim que inicia
        FuncionarioDao dao = new FuncionarioDao();
        ArrayList<Funcionario> func;
        DefaultTableModel tableModel = (DefaultTableModel) jtFunc.getModel();
        int valor = 0;

        boolean status = dao.conectar();
        if(status){
            func = dao.selecionarTodos();  
            while(true){
                try{
                    tableModel.addRow(new Object[] {
                        func.get(valor++),
                        func.get(valor++)
                        });

                }catch(IndexOutOfBoundsException ex){
                    break;
                }
            }
            dao.desconectar();
        }else{
            JOptionPane.showMessageDialog(null, "Não foi possivel conectar ao banco de dados");
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpTabela = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtFunc = new javax.swing.JTable();
        txtPesquisar = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnAtualizar = new javax.swing.JButton();
        btnAvancado = new javax.swing.JButton();

        setClosable(true);
        getContentPane().setLayout(null);

        jpTabela.setLayout(null);

        jtFunc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Cargo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtFunc.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jtFunc.setAutoscrolls(false);
        jtFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtFuncMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtFunc);
        if (jtFunc.getColumnModel().getColumnCount() > 0) {
            jtFunc.getColumnModel().getColumn(0).setResizable(false);
            jtFunc.getColumnModel().getColumn(0).setPreferredWidth(50);
            jtFunc.getColumnModel().getColumn(1).setResizable(false);
            jtFunc.getColumnModel().getColumn(1).setPreferredWidth(280);
        }

        jpTabela.add(jScrollPane1);
        jScrollPane1.setBounds(0, 76, 623, 355);

        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyPressed(evt);
            }
        });
        jpTabela.add(txtPesquisar);
        txtPesquisar.setBounds(12, 13, 432, 40);

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        jpTabela.add(btnPesquisar);
        btnPesquisar.setBounds(451, 13, 90, 40);
        jpTabela.add(jSeparator1);
        jSeparator1.setBounds(0, 62, 620, 10);

        btnAtualizar.setText("Atualizar");
        btnAtualizar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnAtualizar.setMargin(new java.awt.Insets(2, 1, 2, 0));
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        jpTabela.add(btnAtualizar);
        btnAtualizar.setBounds(550, 40, 70, 20);

        btnAvancado.setText("Avançado");
        btnAvancado.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnAvancado.setMargin(new java.awt.Insets(2, 1, 2, 0));
        btnAvancado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancadoActionPerformed(evt);
            }
        });
        jpTabela.add(btnAvancado);
        btnAvancado.setBounds(550, 10, 70, 20);

        getContentPane().add(jpTabela);
        jpTabela.setBounds(0, 0, 630, 420);

        setBounds(0, 0, 639, 461);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        DefaultTableModel tableModel = (DefaultTableModel) jtFunc.getModel();
        int l = 0;
        
        while(l < tableModel.getRowCount()){
            tableModel.removeRow(l);
        }
        prencherTabela();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        FuncionarioDao dao = new FuncionarioDao();
        ArrayList<Funcionario> lista;
        DefaultTableModel tableModel = (DefaultTableModel) jtFunc.getModel();
        
        if(txtPesquisar.getText().equalsIgnoreCase("")){
            btnAtualizar.doClick();
        }else{
            boolean status = dao.conectar();
            int pos = 0, linha = 0;
            
            if(status){
                lista = dao.buscar(txtPesquisar.getText());
                while(linha < tableModel.getRowCount()){
                    tableModel.removeRow(linha);
                }
                while(true){
                    try{
                        tableModel.addRow(new Object[] {
                            lista.get(pos++),
                            lista.get(pos++)
                        });
                    }catch(IndexOutOfBoundsException ex){
                        break;
                    }
                }
            }
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void txtPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnPesquisar.doClick();
        }
    }//GEN-LAST:event_txtPesquisarKeyPressed

    private void btnAvancadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancadoActionPerformed
        TelaAvancadoFunc avancado = new TelaAvancadoFunc();
        avancado.setVisible(true);
        
    }//GEN-LAST:event_btnAvancadoActionPerformed

    private void jtFuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtFuncMouseClicked
        if(evt.getClickCount() == 2){
            TelaAvancadoFunc avancado = new TelaAvancadoFunc(jtFunc.getValueAt(jtFunc.getSelectedRow(), 0).toString(), btnPesquisar);
            avancado.setVisible(true);
        }
    }//GEN-LAST:event_jtFuncMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnAvancado;
    protected javax.swing.JButton btnPesquisar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jpTabela;
    private javax.swing.JTable jtFunc;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
