/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package SubTelas.Func;

import Dao.PendentesDao;
import Dao.UsuarioDao;
import Produto.Login;
import Produto.Pendentes;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cleyt
 */
public class TelaAproFunc extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaAproFunc
     */
    public TelaAproFunc() {
        initComponents();
        listar();
        if(jtPendentes.getRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Não ha nenhuma requisiçao de usuario");
        }
        jpAprov.setVisible(false);
        jpTabela.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpTabela = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPendentes = new javax.swing.JTable();
        jpAprov = new javax.swing.JPanel();
        txtNome = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        cbxCargo = new javax.swing.JComboBox<>();
        btnAprovar = new javax.swing.JButton();
        btnRecusar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        pswSenha = new javax.swing.JPasswordField();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpTabela.setLayout(null);

        jtPendentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pendentes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtPendentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtPendentesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtPendentes);
        if (jtPendentes.getColumnModel().getColumnCount() > 0) {
            jtPendentes.getColumnModel().getColumn(0).setResizable(false);
        }

        jpTabela.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 444, 340);

        getContentPane().add(jpTabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, 450, 340));

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNome.setText("Nome");

        lblSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSenha.setText("Senha");

        lblCargo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCargo.setText("Cargo");

        cbxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Gerente", "Caixa", "Balconista" }));

        btnAprovar.setText("Aprovar");
        btnAprovar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAprovarActionPerformed(evt);
            }
        });

        btnRecusar.setText("Recusar");
        btnRecusar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecusarActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        pswSenha.setEditable(false);

        javax.swing.GroupLayout jpAprovLayout = new javax.swing.GroupLayout(jpAprov);
        jpAprov.setLayout(jpAprovLayout);
        jpAprovLayout.setHorizontalGroup(
            jpAprovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAprovLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAprovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpAprovLayout.createSequentialGroup()
                        .addComponent(btnAprovar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRecusar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpAprovLayout.createSequentialGroup()
                        .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpAprovLayout.createSequentialGroup()
                        .addComponent(lblSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pswSenha))
                    .addGroup(jpAprovLayout.createSequentialGroup()
                        .addComponent(lblCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxCargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jpAprovLayout.setVerticalGroup(
            jpAprovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAprovLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jpAprovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAprovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(pswSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAprovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCargo, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(cbxCargo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpAprovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAprovar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRecusar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        getContentPane().add(jpAprov, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtPendentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtPendentesMouseClicked
        if(evt.getClickCount() == 2){
            if(jtPendentes.getSelectedRow() != -1){
                String funcionario = jtPendentes.getValueAt(jtPendentes.getSelectedRow(), 0).toString();
                mostrar(funcionario);
                jpTabela.setVisible(false);
                jpAprov.setVisible(true);
            }
        }
    }//GEN-LAST:event_jtPendentesMouseClicked

    private void btnAprovarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAprovarActionPerformed
        Login login = new Login();
        PendentesDao Pendentesdao = new PendentesDao();
        UsuarioDao Usuariodao = new UsuarioDao();
        
        login.setUsuario(txtNome.getText());
        login.setSenha(pswSenha.getText());
        if(cbxCargo.getSelectedItem().toString().equalsIgnoreCase("selecione")){
            JOptionPane.showMessageDialog(null, "SELECIONE não é um cargo valido");
            return;
        }else{
            login.setCargo(cbxCargo.getSelectedItem().toString());
        }
        
        boolean statusU = Usuariodao.conectar(), statusP = Pendentesdao.conectar();
        if(statusU){
            int resposta = Usuariodao.salvar(login), resp = Pendentesdao.apagar(login);
            if(resposta == 1){
                if(statusP){
                    if(resp == 1){
                        JOptionPane.showMessageDialog(null, "Usuario aprovado com sucesso");
                        atualizar();
                        jpAprov.setVisible(false);
                        jpTabela.setVisible(true);
                    }else{
                        JOptionPane.showMessageDialog(null, "Não foi possivel apagar o usuario do banco PENDENTES", "Erro", JOptionPane.ERROR);
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Não foi possivel conectar ao banco de dados (pendentes)");
                }
            }else if(resposta == 1062){
                JOptionPane.showMessageDialog(null, "O Usuario já está em uso");
            }else{
                JOptionPane.showMessageDialog(null, "Não foi salvar esse usuario");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Não foi possivel conectar ao banco de dados (usuario)");
        }
        Pendentesdao.desconectar();
        Usuariodao.desconectar();
    }//GEN-LAST:event_btnAprovarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        jpTabela.setVisible(true);
        jpAprov.setVisible(false);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnRecusarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecusarActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "Deseja mesmo recusar o usuario?", "Confirmação", JOptionPane.YES_NO_OPTION);
        
        if(resp == JOptionPane.YES_NO_OPTION){
            
            PendentesDao dao = new PendentesDao();
            Login login = new Login();
            boolean status = dao.conectar();
            
            login.setUsuario(txtNome.getText());            
            
            if(status){
                resp = dao.apagar(login);
                
                if(resp == 1){
                    JOptionPane.showMessageDialog(null, "Usuario Recusado com sucesso");
                    atualizar();
                } else{
                    JOptionPane.showMessageDialog(null, "Não foi possivel recusar esse usuario");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Não foi possivel conectar ao banco de dados");
            }
        }else{            
        }
    }//GEN-LAST:event_btnRecusarActionPerformed

    private void mostrar(String nome){
        PendentesDao dao = new PendentesDao();
        Pendentes pendentes = new Pendentes();
        
        boolean status = dao.conectar();
        if(status){
            pendentes = dao.verificar(nome);
            
            txtNome.setText(pendentes.getUsuario());
            pswSenha.setText(pendentes.getSenha());
        }else{
            JOptionPane.showMessageDialog(null, "Não foi possivel conectar ao banco de dados");
        } 
    }
    
    private void listar(){
        int pos = 0;
        DefaultTableModel tableModel = (DefaultTableModel) jtPendentes.getModel();
        PendentesDao dao = new PendentesDao();
        ArrayList<Pendentes> lista;
        
        boolean status = dao.conectar();
        if(status){
            lista = dao.pendentes();
            while(true){
                try{
                    tableModel.addRow(new Object[]{
                        lista.get(pos++)
                    });
                }catch(IndexOutOfBoundsException ex){
                    break;
                }
            }
            dao.desconectar();
        }else{
            JOptionPane.showMessageDialog(null, "Não foi possivel conectar ao banco de dados");
        }
    }
    
    private void atualizar(){
        int pos = 0;
        DefaultTableModel tableModel = (DefaultTableModel) jtPendentes.getModel();
        
        tableModel.removeRow(jtPendentes.getSelectedRow());
        pos++;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAprovar;
    private javax.swing.JButton btnRecusar;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> cbxCargo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpAprov;
    private javax.swing.JPanel jpTabela;
    private javax.swing.JTable jtPendentes;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JPasswordField pswSenha;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
