/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package SubTelas;

import Commun.TextPrompt;
import Dao.ProdutoDao;
import Produto.Produto;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author cleyt
 */
public class TelaAlterarProd extends javax.swing.JInternalFrame {
    
    public TelaAlterarProd() {
        initComponents();
        atualizarTabela();
        TextPrompt tx = new TextPrompt("Pesquisar", txtPesquisar);
    }

    public JTable getJtProd() {
        return jtProd;
    }

    public void setJtProd(JTable jtProd) {
        this.jtProd = jtProd;
    }
    
    public void atualizarTabela(){
        ProdutoDao dao = new ProdutoDao();
        dao.conectar();
        ArrayList<Produto> produtos = dao.buscar();
        prencherTabela(produtos);
        
    }
    
public void prencherTabela(ArrayList<Produto> produtos) {

    DefaultTableModel tableModel = (DefaultTableModel) jtProd.getModel();    
    for (Produto prod : produtos) {
        tableModel.addRow(new Object[]{
            produtos.get(0),
            produtos.get(1),
            produtos.get(2)
        });
    }
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtProd = new javax.swing.JTable();
        txtPesquisar = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setClosable(true);
        getContentPane().setLayout(null);

        jtProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Produto", "Valor"
            }
        ));
        jScrollPane1.setViewportView(jtProd);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 76, 623, 355);
        getContentPane().add(txtPesquisar);
        txtPesquisar.setBounds(12, 13, 432, 40);

        btnPesquisar.setText("Pesquisar");
        getContentPane().add(btnPesquisar);
        btnPesquisar.setBounds(451, 13, 90, 40);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 62, 620, 10);

        setBounds(0, 0, 639, 461);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jtProd;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
