package SubTelas.Prod;

import Dao.ProdutoDao;
import Produto.Produto;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author cleyt
 */
public class TelaAvancado extends javax.swing.JFrame {

    JButton atualizar;
    
    public TelaAvancado(JButton anterior) {
        initComponents();
        btnEditar.setVisible(false);
        this.atualizar = anterior;
    }
    
    public TelaAvancado(JButton anterior, int cod){
        initComponents();
        mostrar(cod);
        btnConsultar.setEnabled(false);
        txtCod.setEnabled(false);    
        this.atualizar = anterior;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCod = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblCategoria = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();
        lblPreco = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(432, 302));
        setMinimumSize(new java.awt.Dimension(432, 302));
        setResizable(false);
        getContentPane().setLayout(null);

        lblCod.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCod.setText("Código:");
        getContentPane().add(lblCod);
        lblCod.setBounds(20, 22, 75, 37);

        txtCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodKeyPressed(evt);
            }
        });
        getContentPane().add(txtCod);
        txtCod.setBounds(101, 22, 153, 38);

        btnConsultar.setText("Consutar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar);
        btnConsultar.setBounds(260, 23, 106, 37);

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNome.setText("Nome:");
        getContentPane().add(lblNome);
        lblNome.setBounds(20, 66, 75, 37);
        getContentPane().add(txtNome);
        txtNome.setBounds(101, 67, 265, 37);

        lblCategoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCategoria.setText("Categoria");
        getContentPane().add(lblCategoria);
        lblCategoria.setBounds(20, 116, 75, 37);
        getContentPane().add(txtCategoria);
        txtCategoria.setBounds(101, 117, 265, 37);

        lblPreco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPreco.setText("Preço     R$:");
        getContentPane().add(lblPreco);
        lblPreco.setBounds(20, 166, 75, 37);
        getContentPane().add(txtPreco);
        txtPreco.setBounds(101, 167, 265, 37);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(26, 216, 106, 40);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(138, 216, 106, 40);

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(256, 216, 106, 40);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar);
        btnEditar.setBounds(26, 216, 106, 40);

        setSize(new java.awt.Dimension(448, 341));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnConsultar.doClick();
        }
    }//GEN-LAST:event_txtCodKeyPressed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        ProdutoDao dao = new ProdutoDao();
        Produto produto;

        boolean status = dao.conectar();
        if(status){
            try{
                produto = dao.buscar(Integer.parseInt(txtCod.getText()));
            }catch(NumberFormatException ex){
                toBack();
                JOptionPane.showMessageDialog(null, "O codigo não está valido");
                btnEditar.setVisible(false);
                btnSalvar.setVisible(true);
                limpar();
                toFront();
                return;
            }
            if(produto != null){
                txtCod.setText(String.valueOf(produto.getCod()));
                txtNome.setText(produto.getNome());
                txtCategoria.setText(produto.getCategoria());
                txtPreco.setText(String.valueOf(produto.getPreco()));
                btnExcluir.setEnabled(true);
                btnEditar.setVisible(true);
                btnSalvar.setVisible(false);
            }else{
                toBack();
                btnEditar.setVisible(false);
                btnSalvar.setVisible(true);
                JOptionPane.showMessageDialog(null, "Produto não Encontrado");
                limpar();
                toFront();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Erro ao conectar ao banco de dados");
        }
        dao.desconectar();
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        ProdutoDao dao = new ProdutoDao();
        Produto produto = new Produto();
        int resp;
        
        produto.setCod(Integer.parseInt(txtCod.getText()));
        System.out.println(txtCod.getText());
        produto.setNome(txtNome.getText());
        produto.setCategoria(txtCategoria.getText());
        produto.setPreco(Double.parseDouble(txtPreco.getText()));
        
        if(dao.conectar()){
            resp = dao.salvar(produto);
            if(resp == 1){
                toBack();
                resp = JOptionPane.showConfirmDialog(null, "Produto salvo com sucesso deseja salvar mais um?", "Sucesso", JOptionPane.YES_NO_OPTION);
                if(resp == JOptionPane.YES_NO_OPTION){
                    limpar();
                    txtCod.requestFocus();
                    toFront();
                }else{
                    dispose();
                }
            }else{
                toBack();
                JOptionPane.showMessageDialog(null, "Não foi possivel Salvar o produto");
                toFront();
            }
            atualizar.doClick();
        }else{
            JOptionPane.showMessageDialog(null, "Não foi possivel conectar ao banco de dados");
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        ProdutoDao dao = new ProdutoDao();
        
        boolean status = dao.conectar();
        if(status){
            int resp = dao.excluir(Integer.parseInt(txtCod.getText()));
            if(resp == 1){
                toBack();
                JOptionPane.showMessageDialog(null, "Produto Excluido com sucesso");
                btnExcluir.setEnabled(false);
                limpar();
                btnConsultar.setEnabled(true);
                txtCod.setEnabled(true);
                btnEditar.setVisible(false);
                btnSalvar.setVisible(true);
                toFront();
            }else{
                JOptionPane.showMessageDialog(null, "Não foi possivel excluir o produto");
            }
            dao.desconectar();
            atualizar.doClick();
        }else{
            JOptionPane.showMessageDialog(null, "Não foi possivel conectar com o banco de dados");
        }
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        ProdutoDao dao = new ProdutoDao();
        Produto produto = new Produto();
        
        produto.setCod(Integer.parseInt(txtCod.getText()));
        produto.setNome(txtNome.getText());
        produto.setCategoria(txtCategoria.getText());
        produto.setPreco(Double.parseDouble(txtPreco.getText()));
        
        boolean status = dao.conectar();
        if(status){
            int resp = dao.editar(produto);
            if(resp == 1){
                toBack();
                JOptionPane.showMessageDialog(null, "Alteração feita com sucesso");
                toFront();
            }else{
                JOptionPane.showMessageDialog(null, "Não foi possivel salvar as alteração");
            }
            dao.desconectar();
            atualizar.doClick();
        }else{
            JOptionPane.showMessageDialog(null, "Não Foi possivel conectar ao banco de dados");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void mostrar(int cod){
        txtCod.setText(String.valueOf(cod)); 
        btnConsultar.doClick();
    }
    
    private void limpar(){
        txtCod.setText("");
        txtNome.setText("");
        txtCategoria.setText("");
        txtPreco.setText("");
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCod;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPreco;
    // End of variables declaration//GEN-END:variables
}
