package Telas;

import Dao.UsuarioDao;
import Commun.TextPrompt;
import Produto.Login;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

public class TelaLogin extends javax.swing.JFrame {
    UsuarioDao dao = new UsuarioDao();
    TextPrompt tx;
    
    public TelaLogin() {
        initComponents();
        tx = new TextPrompt("Usuario", txtUsuario);
        tx = new TextPrompt("Senha", pswSenha);
        btnEntrar.setToolTipText("Entrar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        pswSenha = new javax.swing.JPasswordField();
        btnCadastro = new javax.swing.JButton();
        btnEntrar = new javax.swing.JButton();
        lblIconMenu = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Acesso ao SIstema");
        setMaximumSize(new java.awt.Dimension(411, 284));
        setMinimumSize(new java.awt.Dimension(411, 284));
        setPreferredSize(new java.awt.Dimension(411, 284));
        getContentPane().setLayout(null);

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/IconUsuario.png"))); // NOI18N
        getContentPane().add(lblUsuario);
        lblUsuario.setBounds(130, 130, 50, 40);

        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
            }
        });
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(180, 130, 290, 41);

        pswSenha.setMaximumSize(new java.awt.Dimension(64, 22));
        pswSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pswSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(pswSenha);
        pswSenha.setBounds(180, 190, 290, 40);

        btnCadastro.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnCadastro.setForeground(new java.awt.Color(0, 0, 255));
        btnCadastro.setText("Cadastra-se");
        btnCadastro.setBorderPainted(false);
        btnCadastro.setContentAreaFilled(false);
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastro);
        btnCadastro.setBounds(460, 400, 110, 40);

        btnEntrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrar);
        btnEntrar.setBounds(130, 260, 350, 40);

        lblIconMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/IconCadeado.png"))); // NOI18N
        lblIconMenu.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblIconMenu);
        lblIconMenu.setBounds(260, 20, 70, 80);

        lblSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/IconCadeadoP.png"))); // NOI18N
        getContentPane().add(lblSenha);
        lblSenha.setBounds(130, 190, 50, 40);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("Não tem um cadastro?");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 410, 130, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BackgroundLogin.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -10, 580, 490);

        setSize(new java.awt.Dimension(593, 488));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        TelaCadastrar cadastro = new TelaCadastrar();
        cadastro.setVisible(true);
    }//GEN-LAST:event_btnCadastroActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        Login login = new Login();
        if (txtUsuario.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Usuario não pode está vazio");
            return;
        } else if (pswSenha.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Senha não pode está vazio");
            return;
        } else{
            login.setUsuario(txtUsuario.getText());
            login.setSenha(pswSenha.getText());
        }
        boolean status;
        status = dao.conectar();
        if (status){
            status = dao.verificar(login);
            if (status){
                TelaMenu menu = new TelaMenu(login);
                menu.setVisible(true);
                dispose();
            } else{
                JOptionPane.showMessageDialog(null, "Login ou senha Errado");
            }
        } else{
            JOptionPane.showMessageDialog(null, "Erro ao conectar ao banco de dados");
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void pswSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswSenhaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnEntrar.doClick();
        }
    }//GEN-LAST:event_pswSenhaKeyPressed

    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            pswSenha.requestFocus();
        }
    }//GEN-LAST:event_txtUsuarioKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblIconMenu;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField pswSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
