
package Telas;

import Dao.ProdutoDao;
import SubTelas.Prod.*;
import SubTelas.Func.*;
import Produto.Login;
import javax.swing.JOptionPane;

/**
 *
 * @author cleyt
 */
public class TelaMenu extends javax.swing.JFrame {

    boolean fechar = false;
    Login login = new Login();
    
    public TelaMenu(){
        initComponents();
    }
    
    public TelaMenu(Login login) {
        initComponents();
        ProdutoDao dao = new ProdutoDao();
        this.login = login;
        nvAcesso(login.getCargo());
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        imgFundo = new javax.swing.JLabel();
        barMenu = new javax.swing.JMenuBar();
        mnuIniciar = new javax.swing.JMenu();
        mnuProd = new javax.swing.JMenu();
        itmCadProd = new javax.swing.JMenuItem();
        itmAltprod = new javax.swing.JMenuItem();
        itmRelaProd = new javax.swing.JMenuItem();
        mnuFunc = new javax.swing.JMenu();
        itmCadFunc = new javax.swing.JMenuItem();
        imtAltFunc = new javax.swing.JMenuItem();
        itmAproFunc = new javax.swing.JMenuItem();
        itmRelaFunc = new javax.swing.JMenuItem();
        itmUsuario = new javax.swing.JMenu();
        itmMudarSenha = new javax.swing.JMenuItem();
        itmSair = new javax.swing.JMenuItem();

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenu2.setText("File");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        jMenu6.setText("jMenu6");

        jMenuItem1.setText("jMenuItem1");

        jMenu7.setText("File");
        jMenuBar3.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar3.add(jMenu8);

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Padaria Manuel");
        getContentPane().setLayout(null);

        imgFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/BackgroundMenu.jpg"))); // NOI18N
        getContentPane().add(imgFundo);
        imgFundo.setBounds(0, 0, 690, 530);

        mnuIniciar.setText("Iniciar");
        mnuIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuIniciarMouseClicked(evt);
            }
        });
        barMenu.add(mnuIniciar);

        mnuProd.setMnemonic('p');
        mnuProd.setText("Produtos");

        itmCadProd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmCadProd.setText("Cadastrar");
        itmCadProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadProdActionPerformed(evt);
            }
        });
        mnuProd.add(itmCadProd);

        itmAltprod.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmAltprod.setText("Alterar e Excluir");
        itmAltprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAltprodActionPerformed(evt);
            }
        });
        mnuProd.add(itmAltprod);

        itmRelaProd.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itmRelaProd.setText("Relatório");
        itmRelaProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmRelaProdActionPerformed(evt);
            }
        });
        mnuProd.add(itmRelaProd);

        barMenu.add(mnuProd);

        mnuFunc.setMnemonic('f');
        mnuFunc.setText("Funcionarios");

        itmCadFunc.setText("Cadastrar");
        itmCadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadFuncActionPerformed(evt);
            }
        });
        mnuFunc.add(itmCadFunc);

        imtAltFunc.setText("Alterar e Excluir");
        imtAltFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imtAltFuncActionPerformed(evt);
            }
        });
        mnuFunc.add(imtAltFunc);

        itmAproFunc.setText("Aprovar");
        itmAproFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAproFuncActionPerformed(evt);
            }
        });
        mnuFunc.add(itmAproFunc);

        itmRelaFunc.setText("Relatorio");
        mnuFunc.add(itmRelaFunc);

        barMenu.add(mnuFunc);

        itmUsuario.setText("Usuario");

        itmMudarSenha.setText("Mudar Senha");
        itmMudarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmMudarSenhaActionPerformed(evt);
            }
        });
        itmUsuario.add(itmMudarSenha);

        itmSair.setText("Sair");
        itmSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmSairActionPerformed(evt);
            }
        });
        itmUsuario.add(itmSair);

        barMenu.add(itmUsuario);

        setJMenuBar(barMenu);

        setSize(new java.awt.Dimension(714, 594));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itmCadProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadProdActionPerformed
        TelaCadastroProd cadProd = new TelaCadastroProd();
        imgFundo.add(cadProd);
        cadProd.setVisible(true);
    }//GEN-LAST:event_itmCadProdActionPerformed

    private void itmAltprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAltprodActionPerformed
        TelaAlterarProd altProd = new TelaAlterarProd();
        imgFundo.add(altProd);
        altProd.setVisible(true);
    }//GEN-LAST:event_itmAltprodActionPerformed

    private void itmRelaProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmRelaProdActionPerformed
        TelaRelatorioProd relaProd = new TelaRelatorioProd();
        imgFundo.add(relaProd);
        relaProd.setVisible(true);
        
    }//GEN-LAST:event_itmRelaProdActionPerformed

    private void itmAproFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAproFuncActionPerformed
        TelaAproFunc aprovacao = new TelaAproFunc();
        imgFundo.add(aprovacao);
        aprovacao.setVisible(true);
    }//GEN-LAST:event_itmAproFuncActionPerformed

    private void imtAltFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imtAltFuncActionPerformed
        TelaAlterarFunc alterar = new TelaAlterarFunc();
        imgFundo.add(alterar);
        alterar.setVisible(true);
    }//GEN-LAST:event_imtAltFuncActionPerformed

    private void itmCadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadFuncActionPerformed
        TelaCadFunc cadFunc = new TelaCadFunc();
        imgFundo.add(cadFunc);
        cadFunc.setVisible(true);
    }//GEN-LAST:event_itmCadFuncActionPerformed

    private void itmSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmSairActionPerformed
        TelaLogin login = new TelaLogin();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_itmSairActionPerformed

    private void itmMudarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmMudarSenhaActionPerformed
        imgFundo.removeAll();
        imgFundo.updateUI();
        TelaMudarSenha mudarSenha = new TelaMudarSenha(login.getUsuario(), login.getSenha());
        imgFundo.add(mudarSenha);
        mudarSenha.setVisible(true);
    }//GEN-LAST:event_itmMudarSenhaActionPerformed

    private void mnuIniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuIniciarMouseClicked
        JOptionPane.showMessageDialog(null, "Em construção", "Alerta", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_mnuIniciarMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void telMenu(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }
    
    
    private void nvAcesso(String cargo){
        if(cargo.equalsIgnoreCase("caixa") | cargo.equalsIgnoreCase("balconista")){
            mnuFunc.setEnabled(false);
            itmCadProd.setVisible(false);
            itmAltprod.setVisible(false);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barMenu;
    private javax.swing.JLabel imgFundo;
    private javax.swing.JMenuItem imtAltFunc;
    private javax.swing.JMenuItem itmAltprod;
    private javax.swing.JMenuItem itmAproFunc;
    private javax.swing.JMenuItem itmCadFunc;
    private javax.swing.JMenuItem itmCadProd;
    private javax.swing.JMenuItem itmMudarSenha;
    private javax.swing.JMenuItem itmRelaFunc;
    private javax.swing.JMenuItem itmRelaProd;
    private javax.swing.JMenuItem itmSair;
    private javax.swing.JMenu itmUsuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JMenu mnuFunc;
    private javax.swing.JMenu mnuIniciar;
    private javax.swing.JMenu mnuProd;
    // End of variables declaration//GEN-END:variables
}
